### ISSUE TITLE
[Node.js] On scalingo-18 this buildpack resolves Node.js to an incompatible version

### ISSUE THREAD

**Issue by johnsudaar** [Scalingo/semver.io#42]
Node 18 broke the compatibility with Ubuntu 18.04 (used by our scalingo-18 stack) see: https://github.com/nodejs/node/issues/42351

Currently any build done on scalingo-18 that needs Node.JS without freezing it to a version <= 17 are failing with the following error:

```
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
```

 Related to [SRE-443]

[SRE-443]: https://scalingo.atlassian.net/browse/SRE-443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by EtienneM** [comment]
The path https://semver.scalingo.com/node-scalingo-18/versions shouldn't resolve versions > 16

**Comment by ipfaze** [comment]
Closing this issue as our stack `scalingo-18` is deprecated and all customer's application are at least on `scalingo-20`.
